extends: airbnb-base
plugins:
  - html
rules:
  no-param-reassign: 0
  func-names: 0
  object-curly-newline: 0
  no-console: 0
  import/no-extraneous-dependencies:
    - error
    -
      devDependencies: true
      optionalDependencies: false
      peerDependencies: false
